version: '3.8'

services:
  wordpress:
    build: ./requirements/wordpress/.
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx/.
    command: nginx -g 'daemon off;'
    volumes:
      - wp_vol:/var/www/html
    ports:
      - 80:80
    depends_on:
      - wordpress
    env_file:
      - .env

  mariadb:
    # container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    # ports:
    #   - 3306:3306
    depends_on:
      - wordpress
    volumes:
      - db_vol:/var/lib/mysql


volumes:
  db_vol:
  wp_vol: