version: '3.8'

services:
  php:
    build: ./srcs/php/.
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - .env

  nginx:
    build: ./srcs/nginx/.
    command: nginx -g 'daemon off;'
    volumes:
      - wp_vol:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php
    env_file:
      - .env

  mariadb:
    # container_name: mariadb
    build: ./srcs/mariadb/.
    env_file:
      - .env
    # ports:
    #   - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql


volumes:
  db_vol:
  wp_vol: