version: '3.8'

services:
  php:
    image: my-php
    command: php -S 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - my-php-volume:/usr/share/nginx/html

  nginx:
    image: my-nginx
    command: nginx -g 'daemon off;'
    volumes:
      - my-php-volume:/usr/share/nginx/html
    ports:
      - "8000:80"
    depends_on:
      - php

  sql:
    image: my-sql
    environment:
      - MARIADB_ROOT_PASSWORD=1
      - MARIADB_USER=1
      - MARIADB_PASSWORD=1
      - MARIADB_DATABASE=1
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  my-php-volume:
  mariadb_data: