FROM debian:latest

RUN apt-get update
RUN apt-get install -y mariadb-server

EXPOSE 3306

LABEL version="1.0"
LABEL description="MariaDB Server"

HEALTHCHECK --start-period=5m \
  CMD /usr/libexec/mysqld --user=root

CMD ["mariadbd"]